include:
  - board: nice_nano_v2  # ← BMP Boostでも、設定はこれでOK！
    shield: torabo_tsuki_lp_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y

  - board: nice_nano_v2  # ← BMP Boostでも、設定はこれでOK！
    shield: torabo_tsuki_lp_right
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
